<a href="https://colab.research.google.com/github/NecipOz/magnimind/blob/main/First_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Due date: Feb 20th Sunday 23.59  Pacific Time

# First assignment 

1. Suppose you invested in Bitcoin at the end of 2020 when Bitcoin gained a lot of value. What would be your money at the end of a week if you had invested $1000 with an average daily increase of 12\% ? You can solve the problem using Python.

**Help**

 * Create a variable capital ($1000)

 * Create a variable for daily growth (12%)

 * Create a variable for period (7)

 * Calculate the final growth rate

 * Calculate result

 * Print result

In [2]:
capital = 1000
daily_growth = 1.12
period = 7
result=1000
i = 0
while i <7:
  result = result * daily_growth
  i += 1
print(result)


2210.6814074060812



2. Get a three digit number the from user and calculate the sum of the digits in the integer.

     user --> 365
    
     output --> "The sum of digits in the number is 14

In [ ]:
num = input("Enter a number: ")
sum = 0
for i in num:
  sum += int(i)
print("The sum of digits in the number is", sum)


Enter a number: 1905
The sum of digits in the number is 15


3. Write some code to calculate the hypotenuse of a right angled triangle. Get the side lengths from the user.

     user --> first side lenth : 6
     
     user --> first side lenth : 8
     
     output --> "The length of the hypotenuse is 10

In [ ]:
side1 = int(input("Enter first side length: "))
side2 = int(input("Enter second side length: "))
hypo = (side1**2 + side2**2)**(0.5)
print("The length of the hypotenuse is",hypo)

Enter first side length: 6
Enter second side length: 8
The length of the hypotenuse is 10.0


4. Get the temperature in Fahrenheit from user and write a code to convert it to Celcius. For conversion, you can use this formula: C = (5/9) * (F - 32)

     Enter the temperature in Fahrenheit: 
            
     user --> 26
    
     output --> Temperature (C) : -3.33

In [ ]:
fahr = int(input("Enter the temperature in Fahrenheit: "))
celc = (5/9)*(fahr-32)
print("Temperature (C) :", celc)

Enter the temperature in Fahrenheit: 26
Temperature (C) : -3.3333333333333335


5. A store charge \\$12 per item if you buy less than 10 items. If you buy between 10 and 99 items, the cost is \\$10 per item. If you buy 100 or more items, the cost is \\$7 per item. Write a program that takes how many items are bought as an input and prints the total cost

In [ ]:
item = int(input("Enter the number of items you bought: "))
total_cost = 0
if item < 10:
  total_cost = 12*item
elif item<100:
  total_cost = 10*item
else:
  total_cost = 7*item
print("Total cost is", total_cost)

Enter the number of items you bought: 15
Total cost is 150


6. Randomly generate a 6 x 6 list that has exactly 12 ones placed in random locations in the list. The rest of the entries should be zeroes. Note you can visualize the 2D list using display function. 

<div>
<img src="attachment:Screen%20Shot%202021-10-02%20at%2017.44.06.png" width="400" height="200" >

In [ ]:
list2d = []
for i in range(6):
  list2d.append([0,0,0,0,0,0])
import random 
list_rand = []
while len(set(list_rand))<12:
  list_rand.append(random.randint(0,35))
list_rand = list(set(list_rand))
for i in list_rand:
  list2d[i//6][i%6] = 1
print(list2d)

[[1, 1, 0, 0, 0, 0], [0, 0, 0, 1, 1, 1], [0, 0, 1, 1, 1, 1], [0, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0]]


In [ ]:
import numpy as np
array1 = np.zeros(36)
while np.sum(array1)<12:
  index = random.randint(0,35)
  array1[index] = 1
print(array1.reshape(6,6))

[[0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1.]
 [0. 1. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


7. A prime number is an integer greater than one that is only divisible by one and itself. Write a function that determines whether or not its parameter is prime, returning True if it is, and False otherwise. Write a main program that reads an integer from the user and displays a message indicating whether or not it is prime. 

In [ ]:
def prime_control(num):
  if num == 2:
    return True
  else:
    for i in range(2,int(num**(0.5)+1)):
      if num % i == 0:
        return False
    return True
prime_control(961748941)

True

8. A year is a leap year if it is divisible by 4, except that years divisible by 100 are not leap years unless they are also divisible by 400. <br>Write a function that takes a year as an input and determines how many leap years there have been between 1600 and that year.

In [ ]:
def leapyear(year):
  if year % 400 == 0:
    return True
  elif year % 100 == 0:
    return False
  elif year % 4 == 0:
    return True
  else:
    return False

count=0
for i in range(1600,2023):
  if leapyear(i):
    count += 1
print("Leap years there have been between 1600 and that year: ",count)


Leap years there have been between 1600 and that year:  103
